import Phaser from 'phaser';

import { USE_PLACEHOLDER_ART } from '../ArtBinding';
import {
  ATLAS,
  BACKGROUND_THEMES,
  bgGroundKey,
  bgRuinsKey,
  bgSkyKey,
} from '../AssetKeys';
import { tuning } from '../data';
import { SceneKeys } from './SceneKeys';

// Zone 1 art, generated by scripts/generate-art.ts and prepared by
// scripts/process-art.ts. Imported so Vite fingerprints and bundles them.
import mechaLegsUrl from '../../assets/sprites/mecha_legs.png';
import mechaTorsoUrl from '../../assets/sprites/mecha_torso.png';
import mechaCannonUrl from '../../assets/sprites/mecha_cannon.png';
import mechaTurretUrl from '../../assets/sprites/mecha_turret.png';
import rustcrawlerUrl from '../../assets/sprites/enemy_rustcrawler.png';
import scavengerBikeUrl from '../../assets/sprites/enemy_scavenger_bike.png';
import platedHulkUrl from '../../assets/sprites/enemy_plated_hulk.png';
import gunnerWalkerUrl from '../../assets/sprites/enemy_gunner_walker.png';
import bossCompactorUrl from '../../assets/sprites/boss_compactor.png';
import projectileShellUrl from '../../assets/sprites/projectile_shell.png';
import scrapPickupUrl from '../../assets/sprites/scrap_pickup.png';
import droneSwarmUrl from '../../assets/sprites/enemy_drone_swarm.png';
import shieldBearerUrl from '../../assets/sprites/enemy_shield_bearer.png';
import ironMatriarchUrl from '../../assets/sprites/boss_iron_matriarch.png';
import incineratorTankUrl from '../../assets/sprites/enemy_incinerator_tank.png';
import burrowerUrl from '../../assets/sprites/enemy_burrower.png';
import eliteVanguardUrl from '../../assets/sprites/enemy_elite_vanguard.png';
import leviathanUrl from '../../assets/sprites/boss_leviathan_engine.png';
import projectileFlakUrl from '../../assets/sprites/projectile_flak.png';
import acidSpitterUrl from '../../assets/sprites/weapon_acid_spitter.png';
import railgunUrl from '../../assets/sprites/weapon_railgun.png';
import bgAshSkyUrl from '../../assets/sprites/bg_ash_canyons_sky.png';
import bgAshRuinsUrl from '../../assets/sprites/bg_ash_canyons_ruins.png';
import bgAshGroundUrl from '../../assets/sprites/bg_ash_canyons_ground.png';
import bgFurnaceSkyUrl from '../../assets/sprites/bg_furnace_sky.png';
import bgFurnaceRuinsUrl from '../../assets/sprites/bg_furnace_ruins.png';
import bgFurnaceGroundUrl from '../../assets/sprites/bg_furnace_ground.png';
import bgRustSkyUrl from '../../assets/sprites/bg_rust_flats_sky.png';
import bgRustRuinsUrl from '../../assets/sprites/bg_rust_flats_ruins.png';
import bgRustGroundUrl from '../../assets/sprites/bg_rust_flats_ground.png';

/**
 * Loads the art.
 *
 * The generated atlas is always loaded: it still supplies every VFX particle,
 * the flak shell, the zone 2 and 3 enemies and their parallax themes, and it is
 * the fallback the whole game drops back to when USE_PLACEHOLDER_ART is true.
 *
 * On top of that, zone 1 gets its AI art as individual textures keyed by the
 * same AssetKeys names. ArtBinding picks whichever exists, so nothing else in
 * the codebase needs to know which set is in play.
 *
 * Hard rule 5 still holds: every texture key comes from AssetKeys.
 */

/** Zone 1 sprites, keyed by their AssetKeys / enemy spriteKey name. */
const ZONE_ONE_SPRITES: ReadonlyArray<readonly [string, string]> = [
  ['mecha_legs', mechaLegsUrl],
  ['mecha_torso', mechaTorsoUrl],
  ['mecha_cannon', mechaCannonUrl],
  ['mecha_turret', mechaTurretUrl],
  ['enemy_rustcrawler', rustcrawlerUrl],
  ['enemy_scavenger_bike', scavengerBikeUrl],
  ['enemy_plated_hulk', platedHulkUrl],
  ['enemy_gunner_walker', gunnerWalkerUrl],
  ['boss_compactor', bossCompactorUrl],
  ['projectile_shell', projectileShellUrl],
  ['scrap_pickup', scrapPickupUrl],
  ['enemy_drone_swarm', droneSwarmUrl],
  ['enemy_shield_bearer', shieldBearerUrl],
  ['boss_iron_matriarch', ironMatriarchUrl],
  ['enemy_incinerator_tank', incineratorTankUrl],
  ['enemy_burrower', burrowerUrl],
  ['enemy_elite_vanguard', eliteVanguardUrl],
  ['boss_leviathan_engine', leviathanUrl],
  ['projectile_flak', projectileFlakUrl],
  ['weapon_acid_spitter', acidSpitterUrl],
  ['weapon_railgun', railgunUrl],
];

/** All three zones' parallax now comes from the AI set. */
const AI_BACKGROUNDS: ReadonlyArray<readonly [string, string]> = [
  [bgSkyKey('rust_flats'), bgRustSkyUrl],
  [bgRuinsKey('rust_flats'), bgRustRuinsUrl],
  [bgGroundKey('rust_flats'), bgRustGroundUrl],
  [bgSkyKey('ash_canyons'), bgAshSkyUrl],
  [bgRuinsKey('ash_canyons'), bgAshRuinsUrl],
  [bgGroundKey('ash_canyons'), bgAshGroundUrl],
  [bgSkyKey('furnace'), bgFurnaceSkyUrl],
  [bgRuinsKey('furnace'), bgFurnaceRuinsUrl],
  [bgGroundKey('furnace'), bgFurnaceGroundUrl],
];

export class PreloadScene extends Phaser.Scene {
  constructor() {
    super(SceneKeys.Preload);
  }

  preload(): void {
    this.showProgress();

    this.load.atlas(ATLAS, 'art/sprites.png', 'art/sprites.json');

    // The fallback path: generated strips for every theme, no AI art at all.
    if (USE_PLACEHOLDER_ART) {
      for (const theme of BACKGROUND_THEMES) {
        this.load.image(bgSkyKey(theme), `art/bg_${theme}_sky.png`);
        this.load.image(bgRuinsKey(theme), `art/bg_${theme}_ruins.png`);
        this.load.image(bgGroundKey(theme), `art/bg_${theme}_ground.png`);
      }
      return;
    }

    for (const [key, url] of ZONE_ONE_SPRITES) {
      this.load.image(key, url);
    }
    for (const [key, url] of AI_BACKGROUNDS) {
      this.load.image(key, url);
    }
  }

  create(): void {
    this.scene.start(SceneKeys.MainMenu);
  }

  private showProgress(): void {
    const { baseWidth, baseHeight } = tuning.world;
    const barWidth = baseWidth * 0.36;
    const left = (baseWidth - barWidth) * 0.5;
    const top = baseHeight * 0.5;

    this.add
      .text(baseWidth * 0.5, top - 34, 'SCRAP TITAN', {
        fontFamily: 'monospace',
        fontSize: '30px',
        color: '#c9a227',
      })
      .setOrigin(0.5);

    this.add
      .rectangle(left, top, barWidth, 12, 0x1a1512)
      .setOrigin(0, 0)
      .setStrokeStyle(2, 0x6f6a62);

    const fill = this.add.rectangle(left + 2, top + 2, 0, 8, 0xc9a227).setOrigin(0, 0);

    this.load.on(Phaser.Loader.Events.PROGRESS, (value: number) => {
      fill.width = (barWidth - 4) * value;
    });
  }
}
