import Phaser from 'phaser';

import { USE_PLACEHOLDER_ART } from '../ArtBinding';
import {
  ATLAS,
  BACKGROUND_THEMES,
  bgGroundKey,
  bgRuinsKey,
  bgSkyKey,
} from '../AssetKeys';
import { tuning } from '../data';
import { SceneKeys } from './SceneKeys';

// Zone 1 art, generated by scripts/generate-art.ts and prepared by
// scripts/process-art.ts. Imported so Vite fingerprints and bundles them.
import mechaLegsUrl from '../../assets/sprites/mecha_legs.png';
import mechaTorsoUrl from '../../assets/sprites/mecha_torso.png';
import mechaCannonUrl from '../../assets/sprites/mecha_cannon.png';
import mechaTurretUrl from '../../assets/sprites/mecha_turret.png';
import rustcrawlerUrl from '../../assets/sprites/enemy_rustcrawler.png';
import scavengerBikeUrl from '../../assets/sprites/enemy_scavenger_bike.png';
import platedHulkUrl from '../../assets/sprites/enemy_plated_hulk.png';
import gunnerWalkerUrl from '../../assets/sprites/enemy_gunner_walker.png';
import bossCompactorUrl from '../../assets/sprites/boss_compactor.png';
import projectileShellUrl from '../../assets/sprites/projectile_shell.png';
import scrapPickupUrl from '../../assets/sprites/scrap_pickup.png';
import bgRustSkyUrl from '../../assets/sprites/bg_rust_flats_sky.png';
import bgRustRuinsUrl from '../../assets/sprites/bg_rust_flats_ruins.png';
import bgRustGroundUrl from '../../assets/sprites/bg_rust_flats_ground.png';

/**
 * Loads the art.
 *
 * The generated atlas is always loaded: it still supplies every VFX particle,
 * the flak shell, the zone 2 and 3 enemies and their parallax themes, and it is
 * the fallback the whole game drops back to when USE_PLACEHOLDER_ART is true.
 *
 * On top of that, zone 1 gets its AI art as individual textures keyed by the
 * same AssetKeys names. ArtBinding picks whichever exists, so nothing else in
 * the codebase needs to know which set is in play.
 *
 * Hard rule 5 still holds: every texture key comes from AssetKeys.
 */

/** Zone 1 sprites, keyed by their AssetKeys / enemy spriteKey name. */
const ZONE_ONE_SPRITES: ReadonlyArray<readonly [string, string]> = [
  ['mecha_legs', mechaLegsUrl],
  ['mecha_torso', mechaTorsoUrl],
  ['mecha_cannon', mechaCannonUrl],
  ['mecha_turret', mechaTurretUrl],
  ['enemy_rustcrawler', rustcrawlerUrl],
  ['enemy_scavenger_bike', scavengerBikeUrl],
  ['enemy_plated_hulk', platedHulkUrl],
  ['enemy_gunner_walker', gunnerWalkerUrl],
  ['boss_compactor', bossCompactorUrl],
  ['projectile_shell', projectileShellUrl],
  ['scrap_pickup', scrapPickupUrl],
];

/** The rust flats parallax, which the AI set replaces wholesale. */
const ZONE_ONE_BACKGROUNDS: ReadonlyArray<readonly [string, string]> = [
  [bgSkyKey('rust_flats'), bgRustSkyUrl],
  [bgRuinsKey('rust_flats'), bgRustRuinsUrl],
  [bgGroundKey('rust_flats'), bgRustGroundUrl],
];

export class PreloadScene extends Phaser.Scene {
  constructor() {
    super(SceneKeys.Preload);
  }

  preload(): void {
    this.showProgress();

    this.load.atlas(ATLAS, 'art/sprites.png', 'art/sprites.json');

    // Themes the AI set does not cover keep their generated strips.
    for (const theme of BACKGROUND_THEMES) {
      if (theme === 'rust_flats' && !USE_PLACEHOLDER_ART) continue;
      this.load.image(bgSkyKey(theme), `art/bg_${theme}_sky.png`);
      this.load.image(bgRuinsKey(theme), `art/bg_${theme}_ruins.png`);
      this.load.image(bgGroundKey(theme), `art/bg_${theme}_ground.png`);
    }

    if (USE_PLACEHOLDER_ART) return;

    for (const [key, url] of ZONE_ONE_SPRITES) {
      this.load.image(key, url);
    }
    for (const [key, url] of ZONE_ONE_BACKGROUNDS) {
      this.load.image(key, url);
    }
  }

  create(): void {
    this.scene.start(SceneKeys.MainMenu);
  }

  private showProgress(): void {
    const { baseWidth, baseHeight } = tuning.world;
    const barWidth = baseWidth * 0.36;
    const left = (baseWidth - barWidth) * 0.5;
    const top = baseHeight * 0.5;

    this.add
      .text(baseWidth * 0.5, top - 34, 'SCRAP TITAN', {
        fontFamily: 'monospace',
        fontSize: '30px',
        color: '#c9a227',
      })
      .setOrigin(0.5);

    this.add
      .rectangle(left, top, barWidth, 12, 0x1a1512)
      .setOrigin(0, 0)
      .setStrokeStyle(2, 0x6f6a62);

    const fill = this.add.rectangle(left + 2, top + 2, 0, 8, 0xc9a227).setOrigin(0, 0);

    this.load.on(Phaser.Loader.Events.PROGRESS, (value: number) => {
      fill.width = (barWidth - 4) * value;
    });
  }
}
